### PR TITLE
Add PHP 8 compatibility

### LINKED ISSUE #42: PHP 8.0 compatibility
Currently composer.json requires php ^7.2.5. For PHP 8 that won't work. 

Changing it to:

```json
"php": "^7.2.5|^8.0",
```

Would probably already solve it. Would you accept a PR for PHP 8 compatiblity?

### PR DESCRIPTION
**Pull request by dvdheiden**
I think this would do the job. Closes #42

### CODE REVIEW

**Comment by hyperized** [comment]
I see `phpcs` fails with Scrutinizer, I suspect more tests will fail. This package is in need of some upgrading. Can you work with your fork in the meantime so I can spend some time making this code 7.4 and 8.0 compatible?

**Comment by dvdheiden** [comment]
Yes the package should be upgraded fully instead of just making it compatible. Maybe use https://github.com/rectorphp/rector?

**Comment by hyperized** [comment]
I have been working on a rewrite: https://github.com/hyperized/hostfact/pull/28 but that's gone stale. I see Hostfact also released the 3.0 version of their API. I think the time has come to close #28 and merge the efforts into a 3.0 push :D. Let me see what I can do!

**Comment by hyperized** [comment]
Closed, superseded by: https://github.com/hyperized/hostfact/releases/tag/v3.0.0

**Pull request closed without merging**
